[project]
name = "illo"
version = "2.1.0"
description = "AI-Powered UFO Controller for Adafruit Circuit Playground Bluefruit"
authors = [
    {name = "Charles Doebler", email = "charles@feralcatai.com"}
]
license = {text = "MIT"}
readme = "README.md"
keywords = [
    "circuitpython", 
    "ai", 
    "iot", 
    "led", 
    "bluetooth", 
    "adafruit",
    "music",
    "interactive",
    "college",
    "embedded"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: End Users/Desktop",
    "Topic :: System :: Hardware",
    "Topic :: Artistic Software",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Multimedia :: Sound/Audio :: Analysis",
    "Topic :: Games/Entertainment",
    "Topic :: Home Automation",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: Implementation :: MicroPython"
]
requires-python = ">=3.7"

[project.urls]
homepage = "https://github.com/cdoebler1/ILLO"
repository = "https://github.com/cdoebler1/ILLO"
documentation = "https://github.com/cdoebler1/ILLO/blob/main/README.md"
"Bug Reports" = "https://github.com/cdoebler1/ILLO/issues"
"Source" = "https://github.com/cdoebler1/ILLO"

# CircuitPython specific configuration
[tool.circuitpython]
target_board = "circuitplayground_bluefruit"
main_file = "code.py"
required_libraries = [
    "adafruit_circuitplayground",
    "neopixel", 
    "adafruit_ble",
    "adafruit_bluefruit_connect",
    "simpleio"
]

# Hardware specifications
[hardware]
board = "Adafruit Circuit Playground Bluefruit"
circuitpython_version = ">=7.0.0"
flash_memory = "2MB"
ram_memory = "256KB"
features = [
    "bluetooth",
    "neopixels", 
    "accelerometer",
    "microphone",
    "buttons",
    "switch"
]

# Operating modes configuration
[modes]
default_mode = "ufo_intelligence"
available_modes = [
    "ufo_intelligence",
    "intergalactic_cruising", 
    "meditate",
    "dance_party"
]

# AI system settings
[ai_system]
learning_enabled = true
memory_persistence = true
personality_development = true
interaction_tracking = true
college_integration = true

# Music system configuration
[music_system]
chant_detection = true
fight_song_recognition = true
beat_synchronization = true
college_colors = true
tempo_matching = true

# Development tools
[tool.black]
line-length = 100
target-version = ['py37']

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --tb=short"